### ISSUE TITLE
Field is missing from REST API 

### ISSUE THREAD

**Issue by Dathix** [Log1x/acf-phone-number#61]
Hey Brandon, first of all, huge thanks for all your fantastic work!

Recently I discovered that the field is missing from the REST API.

I fixed it by using `acf_register_field_type` instead of the two filters. 
Maybe I am missing something but everything seems to work fine.

All the best,
Daniel

**Comment by Log1x** [comment]
You're right. `acf_register_field_type()` appears to be the new thing with 6.x – I hadn't realized. Do you want to do a PR?

Otherwise I can get a fix pushed out to all of my plugins sometime tonight.

What kind of result are you seeing with the Rest API and the Phone Number instance? Is it working as intended for you? Haven't used ACF alongside the Rest API so now sure how it works when it's not returning an array or text value by default.

**Comment by Dathix** [comment]
Already create one in the meantime. 

It works fine by default but if you add `acf_format=standard` parameter to the request it breaks the formatting because it will use `acf_format_value()`.

This is why I added `acf/rest/format_value_for_rest/type` filter to make sure it will always return the unformatted value.
